// buildInfo.js — the phase/version label and changelog shown in the Settings
// drawer's "Build" panel. Hand-maintained: bump PHASE/VERSION and prepend a
// note each time a phase ships, so a returning GM can see at a glance what
// changed without digging through git history.

export const BUILD = {
  phase: '7',
  version: '0.7.0',
  label: 'Phase 7 begins: tag dropdown + vocabulary; two bug fixes',
  notes: [
    'Phase 7 (Context Graph depth) begins — tag fields as dropdowns: an entity\'s tags now render as removable chips plus a dropdown of tags already used by other entities of the same type (domain/entities.js\'s listTagVocabulary, computed live off existing entities — no separate stored vocabulary to drift out of sync). Selecting a listed tag adds it immediately; "+ New…" still takes a one-time freeform name via prompt, same pattern as "+ Field"/"+ Track" elsewhere. Replaces the old plain comma-separated text input.',
    'Fixed: a statblock value (or any text/tag field) typed but never blurred — then the browser was refreshed, closed, or the tab switched away — was silently lost, since every field only commits on the \'change\' event (fires on blur). Root-caused via a direct Playwright repro (typed a value into an attribute field, reloaded without tabbing away first, confirmed the edit reverted to its old value) after ruling out data-loss in the normal add-group/edit-value/refresh flow across file:// and http://, and across an actual rebuild. Fixed with one small addition in ui/shell.js\'s mountShell(): a \'beforeunload\'/\'visibilitychange\' listener blurs the currently-focused field, firing its pending \'change\' through the existing delegated handler — no new commit path, no per-element listeners added. This is what looked like "added statblocks are not retained" — the groups themselves were always saved instantly on click; it was in-progress field edits (a just-typed attribute value, an NPC\'s just-typed #character tag) that could be lost.',
    '5PFH dice roll toast now shows the breakdown, not just the combined total: "d6(2) + 0 = 2 vs target 6 → Fail" instead of "Fail — 2 vs target 6" — matching what the Journal entry already showed. `ui/shell.js`\'s `performFieldRoll` (\'flat\' branch) only — Starforged/Traveller toasts unchanged, not reported as an issue.',
    'Phase 6 complete — Narrative Trackers: two new campaign-level dials, Resources and Reputation (context.what, alongside threat/mystery — same "GM-set gauge the Co-Pilot reads" pattern, defaulting to a neutral 5/10 midpoint rather than 0 so an old save never suddenly reads as destitute or reviled). New Shift Story actions (Gain/Spend Resources, Raise/Lower Reputation) and two range sliders on the WHAT view. The Co-Pilot now reacts to both: critically low Resources surfaces a scarcity observation/consequence and points at the Trade & Cargo > Cargo Problem oracle table; soured Reputation surfaces as an observation/consequence about closed doors and refused help; abundant Resources or high Reputation open a new opportunity line (a favor, discount, or the room to be generous). This closes out Phase 6 (Campaign Continuity) — Session Recap, Thread lifecycle, and "What did I overlook?" all shipped in prior builds this phase.',
    'Attribute fields (Edge, Combat, Speed, ...) redesigned: the +/- steppers are gone in favor of a directly-editable, numerically-validated input (no min/max clamp — a modifier can go negative or past an old 1-5 scale). Three per-field display formats, editable in Settings\' Bestiary template editor: sign ("+3", Starforged-style, default), inches ("3\"", 5PFH Speed-style), plain ("3"). The field\'s LABEL is now the roll trigger (click "EDGE" to roll); a field with no roll method gets a plain, non-clickable label. Four dice models now available (none/Starforged d6-vs-2d10/5PFH d6-vs-target/new Traveller 2d6-vs-target, domain/dice.js\'s rollTraveller) — room is left to add more (5PFH Planetfall, Stars Without Number) as those systems get authored mechanics. 5PFH\'s Speed field ships as the concrete example: inches-formatted, not rollable.',
    'Phase 6 continued — Thread lifecycle: domain/threads.js threads now carry a 7-state narrative stage (Seeded/Active/Escalating/Dormant/Converging/Resolved/Archived) and a low/normal/high priority, GM-set via dropdowns on the Threads block (WHY question) — never auto-inferred, except that filling a clock still auto-marks it Resolved (unchanged prior behavior). "What did I overlook?" — a new Co-Pilot card (observation-only, never auto-correcting) surfaces threads gone quiet (Dormant, or untouched since creation), excluding ones already Resolved/Archived.',
    'Rules Constitution — requirements/gameplay-goals.md sharpened "genre-aware, not genre-locked" into a concrete claim: every ruleset is a content provider, not the application. data/rulesConstitution.js records six named systems (Starforged, Traveller, Five Parsecs From Home, Hostile, Stars Without Number, Planetfall) mapped to gameplay areas, plus four responsibilities reserved for Saga Atlas itself (campaign memory, story continuity, rules switching, recommendations) — never delegated to a ruleset. Surfaced read-only in Settings; each provider honestly status-tagged (two of the six have zero authored data yet). Reference for Phase 9\'s future Activity → Rules Lens recommender, not an engine built ahead of its turn — see docs/adr/0002.',
    'Phase 6 (Campaign Continuity) begins — Session Recap ("Previously on...", domain/recap.js): one click in the Journal drawer composes what happened last time, open threads, the current objective, relevant entities, pressure, and a Co-Pilot recommendation from data already kept; "Save as Journal note" files it, excluding prior recaps from its own recap. Pure, read-only, and tested. Remaining Phase 6 items (Narrative Trackers beyond threat/mystery) are still open.',
    'Statblock polish — Bestiary is now explicitly an NPC subtype (like Character): statblock add-choices are scoped by entity type (Character Sheet/Bestiary only for NPCs, Vehicle Stats only for Assets; other entity types get no statblock options). Attribute/stat fields (Edge, Combat, ...) now render as a single signed number with +/- steppers instead of a 1-5 click-to-set meter — matching how Starforged/5PFH sheets actually present a stat; the 1-5 track remains for genuine depleting resources (Health, Hull). The "+ Add a statblock" chip row collapses behind a gear icon to save space once a few groups exist.',
    'Statblock redesign — an entity now holds an ARRAY of statblock groups (entity.statblocks) instead of one: a character can carry both a Starforged and a 5PFH sheet, or an NPC two Bestiary templates, simultaneously — adding one is always additive (a "+ Add" chip row), never a toggle that replaces another\'s data; each group is removable on its own via its own trash icon. Per-field UI simplified to label + value only — the rename input and the ★ (attribute)/Aa (track)/✕ (remove) buttons are gone from the entity view, since a field\'s name/kind is now fixed by its template (Settings owns that); ad-hoc "+ Field"/"+ Track" additions are named via a one-time prompt instead of an inline-editable label.',
    'Phase 5 audit — browser-verified every Phase 5 feature end to end (Playwright against the real bundle). Found and fixed one real bug: the in-app PDF viewer\'s close button was rendered but unclickable — the always-open Documents drawer sat at a higher z-index and physically overlapped it. The viewer now insets its right edge by the current drawer\'s width instead of extending underneath it.',
    'Phase 5 — design review pass against PROGRESS.md USER NOTES: three new drawers — Party (NPC #character roster + party-wide resource trackers), Colony (5PFH Planetfall turn sheet, entity-referencing crew roster, #lifeform encounter filter), Guide (freeform @mention/@[Doc]-linked reference document). Oracle drawer rebuilt as a grouped, collapsible, searchable tree (was a flat un-filterable list — the search box was silently broken). Bestiary statblock templates: per-game-system NPC field manifests (kind, roll method, sort order) editable in Settings, with a per-NPC template selector so a Bestiary can assign the right ruleset per creature; attribute badges now show a signed value ("EDGE +3"). Document Library: multi-file upload, tags + tag-filter + search, rename-the-label (not the file) via an edit button, name-as-link opening an in-app PDF viewer panel (not a new tab) beside the drawer. Entity relationships gained an editable free-text note per link. Fixed: a missing import that threw whenever the Journal rendered an entry with a @[Document] mention; the service worker cache-first strategy that could mask a rebuilt bundle indefinitely (now network-first); a GitHub Pages deploy of this repo having no dist/ bundle at all (added a build+deploy Actions workflow).',
    'Phase 4 — Document Library: assets/docs/ is auto-scanned at build time into a Reference Library (rulebooks/settings PDFs, always current with the folder); the docs drawer also supports real file uploads (stored as data URLs) alongside text notes. Character Sheets: a ruleset-driven statblock kind (Starforged or 5PFH, chosen in Settings > Stat system) builds a full rollable stat/resource-track sheet in one click, switchable between rulesets; an optional Crew Link link-out lives in Settings for full character-building wizards this app does not replicate.',
    'Phase 3D — statblock fields can be numeric tracks: a Crew-Link-style row of click-to-set boxes, with double-click on the value badge to roll (d6 + value vs 2 challenge dice, filed to the Journal). Health/Hull default to tracks; any field converts with the # / Aa toggle; "+ Track" adds a new one.',
    'Phase 3C — NPC/vehicle statblocks, drag-and-drop entity linking + drop-to-mention in Journal and context fields, this Build panel.',
    'Phase 3B — force-directed relationship graph over entity links, click-through to inspector, live edge-tab badges.',
    'Phase 3A — Entity Inspector + @mention auto-linking; WHO/WHERE cards populate from real entities.',
    'New — Threads (progress clocks) with Co-Pilot awareness.',
    'Phase 2 — interactive cockpit: Continue Story, Shift Story reducers, Oracle + Journal drawers, live Co-Pilot, timeline.',
    'Phase 1 — oracle roll engine, scene generation, context model ported as pure, tested modules.',
    'Phase 0 — single versioned campaign document, lossless migration from v0.53, three-tier cockpit shell.',
  ],
};
