// buildInfo.js — the phase/version label and changelog shown in the Settings
// drawer's "Build" panel. Hand-maintained: bump PHASE/VERSION and prepend a
// note each time a phase ships, so a returning GM can see at a glance what
// changed without digging through git history.

export const BUILD = {
  phase: '9',
  version: '0.9.1',
  label: 'Reliability + UX pass: tabbed drawers, 3-tier responsive, touch drag-drop, PWA audit',
  notes: [
    '2026-07-04 reliability + UX pass, run after a full regression check confirmed Phase 9\'s Activity picker and everything before it: (1) Settings shows campaign storage size + a "Restore last backup" button (store.js\'s storageInfo()/restoreBackup() — the one-slot backup from ADR 0005 had no restore UI until now). (2) The Pages deploy workflow gained a post-deploy smoke check that fetches the live site and verifies the bundle actually resolves, plus (added the same day) a check that a sample LFS-tracked PDF resolves to real content, not a pointer file. (3) The Reference Library\'s PDFs (~445MB) moved to Git LFS, including a history rewrite (backed by a mirror clone, confirmed via a fresh clone afterward) — caught and fixed a real regression this surfaced (actions/checkout needs lfs:true or LFS files deploy as pointer text). (4) Drawers are now tabbed: multiple can stay pinned open at once (openDrawers/activeDrawer replacing the old single openDrawer), with a tab strip that only appears once 2+ are open. (5) Three real responsive tiers instead of one: tablet (768-1023px) now gets a Co-Pilot side panel that slides in from the edge like a drawer, distinct from phone\'s (<768px) bottom sheet. (6) Two keyboard shortcuts: Escape (close whatever\'s topmost) and Ctrl/Cmd+K (open Universal Search). (7) Touch drag-and-drop: a gesture recognizer for entity linking and @mention-by-drag now works on real touch devices (HTML5 DnD never fires for touch at all), sharing the same completeDrop() logic the mouse path uses — see docs/mobile-drag-drop-test-cases.md for the manual device checklist. (8) A PWA installability audit (Chrome DevTools Protocol, not just eyeballing the manifest) came back clean — zero installability errors, service worker/offline mode both verified by actually going offline and reloading — except the app icon still read "SA" (leftover Saga Atlas branding); regenerated as "GM" in the exact same style.',
    'Phase 9 (Activity-driven gameplay) begins — the HOW workspace question gains an Activity picker (Explore/Investigate/Negotiate/Travel/Trade/Combat/Faction dealings/Downtime/Horror/World-building, new domain/activities.js) that turns data/rulesConstitution.js\'s Rules Constitution from a read-only Settings reference into an actual recommender: picking an Activity looks up its registered gameplay area and shows the Rules Lens provider(s) responsible for it (e.g. Combat -> Five Parsecs From Home), with a "Use as default" button that sets settings.statRuleset — suggestion only, never automatic, extending the existing per-entity ruleset selector rather than replacing it. Genre packs (this phase\'s other item) remain open.',
    'Root cause found and fixed (the previous build\'s toast surfaced the symptom; this fixes the real bug): store.js\'s persist() wrote a full duplicate of the previous save to a backup key BEFORE writing the real one — momentarily needing quota for two whole copies of the campaign at once. Once a campaign (typically one with large embedded document uploads) crossed roughly half of localStorage\'s quota, that backup write started failing, and because it was treated as fatal, it silently blocked EVERY subsequent save — including something as simple as clicking to select a Cast entity — even though the real save alone would still have fit. Confirmed via a live error report ("Failed to execute \'setItem\' on \'Storage\': Setting the value of \'sagaatlas.campaign.backup\' exceeded the quota") and reproduced deterministically (forced only the backup key\'s write to throw; confirmed the real save failed too, then confirmed it succeeds under the fix, including surviving a reload). The backup write is now best-effort — if it can\'t fit, it\'s skipped (logged, not thrown) and the actual campaign save proceeds; the backup has no restore UI wired to it yet, so a skipped backup costs nothing today, but a blocked real save cost everything.',
    'Fixed: any interaction that saves (store.update() — includes something as simple as clicking to select a Cast entity) writes the whole campaign document to localStorage; if that write fails (most commonly localStorage quota exceeded — real-world cause: large uploaded PDFs stored as embedded data, see store.js\'s persist()), the change was correctly rolled back but this threw with no visible feedback, so the click just looked like it did nothing. Root-caused via a deterministic repro (forced localStorage.setItem to throw, confirmed clicking a Cast row silently failed to select while filter-only interactions — pure in-memory state, no save involved — kept working, matching a real report: "filter works, select doesn\'t"). Fixed at the one choke point every interaction already passes through (ui/shell.js\'s single delegated click/change/input/dblclick listeners, rule 4): a `guarded()` wrapper now catches any handler failure and shows a toast ("Couldn\'t save — ... Storage may be full; try exporting your campaign as a backup") instead of swallowing it silently. If you\'re seeing this: export your campaign (Settings → Export Campaign JSON) as a backup, then free up space by removing large uploaded documents (or moving big rulebooks into assets/docs/ + rebuild instead, which has no storage-quota limit).',
    'Phase 8 (Unified Discovery) complete — four items: (1) Universal Search: a new 🔍 Search button in the header opens an overlay searching entities, journal, oracle tables (names and individual entries), documents (uploaded/text + Reference Library), Party trackers, and Colony fields/crew in one query (domain/search.js\'s universalSearch(), pure and DOM-free — it returns declarative targets, ui/searchPanel.js and shell.js do the navigating); clicking a result jumps straight to it (opens the entity, the document tab, or the Oracle drawer pre-filtered to the matched table). (2) Oracle table editor: each table in the Oracle drawer gets an ✎ toggle to add/edit/remove its entries and a "↺ Reset to default" once changed, built on the existing oracles.overrides mechanism (no second data path) — the drawer\'s tree also now reads through tablesWithOverrides so an edited table displays correctly, not just rolls correctly. Two new content additions shipped alongside it: a "Scenario Framing" oracle group (Dilemma/Objective/Framing NPCs/Map Feature) and an "Environmental Hazards" group (25-entry Environmental Event table + Survey Problem table), both original content. (3) Cast drawer gained a name/tag search box and entity-type filter chips above the list. (4) NPC generation oracle chain: the existing Characters oracle group (Role/Goal/Revealed Aspect/Disposition) gained a Name table to complete the chain, and a new 🎲 Generate NPC button (domain/session.js\'s generateNpc()) rolls all five into a new NPC in one click — plus a 5PFH-style Patron Benefit/Hazard/Danger Pay job-offer table set under Missions.',
    'Fixed: a Cast-list row was both the click target (select this entity) AND the drag source (draggable="true", to create a relationship) — for a real mouse, a few pixels of jitter between mousedown and mouseup is enough for the browser to start a native drag instead of firing a click, which suppressed selection entirely and made the whole Cast list feel unresponsive (reported: "clicking an entity does not make it active, dragging does not work either"). Dragging is now confined to a small ⠿ grip inside each row; the row itself is click-only (drop targets never needed draggable in the first place). The Relationships section\'s "Link" button is now icon-labeled (🔗 Link), and each relationship\'s remove control is titled "Remove link" for clarity. The Cast drawer\'s entity list can now be collapsed to just a header (▸ Cast — N entities · editing X) via a toggle, leaving the full inspector for the active entity with more room.',
    'Phase 7 (Context Graph depth) complete — three more items: (1) Typed/weighted relationships: a relationship now carries a semantic type (Linked/Member Of/Owns/Controls/Located At/Allied With/Rival Of/Bond, domain/entities.js\'s RELATIONSHIP_TYPES) alongside its free-text label, plus a 0-10 strength weight — a Starforged Bond is just a `bond`-typed relationship whose strength a GM raises over time, not a second mechanism. The requested type applies only to the side that requested it (per-side, like the existing label editor); every pre-existing relationship normalizes to linked/0 the moment any setter touches it. (2) "Flag, don\'t delete" invalid relationships (pack 9): a directional type (Member Of/Owns/Controls/Located At) implies a target entity type; when the target\'s own type is edited out from under it, the relationship chip gets a ⚠ (tooltip explains why) and the Co-Pilot gains a "Relationships to review" card — nothing is auto-corrected or removed. (3) Faction card template: faction entities gain hq/leadership/scenarioSeed fields (Hostile\'s "Agencies & Corporations" pattern, Setting pp.79-111), shown as a "Faction card" section in the inspector.',
    '`@` pointers into documents gain page anchors: `@[Doc Title#12]` or `@[Doc Title p.12]` names a page alongside the title (domain/documents.js\'s parseDocumentMentionRefs). A document badge that resolves to an openable PDF — an uploaded/library file or a Reference Library entry, whichever matches the title (findDocumentTabByTitle) — now renders as a clickable button (Journal entries, Guide) that opens the existing in-app viewer and jumps straight to that page via a `#page=N` fragment (openDocumentTab/resolveDocumentTab track a per-tab requested page); re-focusing an already-open tab without a page anchor leaves it wherever it already is. A text-note document mention still renders as a plain, non-clickable badge, same as before. Closes out the last piece of the old "@ pointers... like the ChatGPT version did" ask.',
    'Phase 7 (Context Graph depth) begins — tag fields as dropdowns: an entity\'s tags now render as removable chips plus a dropdown of tags already used by other entities of the same type (domain/entities.js\'s listTagVocabulary, computed live off existing entities — no separate stored vocabulary to drift out of sync). Selecting a listed tag adds it immediately; "+ New…" still takes a one-time freeform name via prompt, same pattern as "+ Field"/"+ Track" elsewhere. Replaces the old plain comma-separated text input.',
    'Fixed: a statblock value (or any text/tag field) typed but never blurred — then the browser was refreshed, closed, or the tab switched away — was silently lost, since every field only commits on the \'change\' event (fires on blur). Root-caused via a direct Playwright repro (typed a value into an attribute field, reloaded without tabbing away first, confirmed the edit reverted to its old value) after ruling out data-loss in the normal add-group/edit-value/refresh flow across file:// and http://, and across an actual rebuild. Fixed with one small addition in ui/shell.js\'s mountShell(): a \'beforeunload\'/\'visibilitychange\' listener blurs the currently-focused field, firing its pending \'change\' through the existing delegated handler — no new commit path, no per-element listeners added. This is what looked like "added statblocks are not retained" — the groups themselves were always saved instantly on click; it was in-progress field edits (a just-typed attribute value, an NPC\'s just-typed #character tag) that could be lost.',
    '5PFH dice roll toast now shows the breakdown, not just the combined total: "d6(2) + 0 = 2 vs target 6 → Fail" instead of "Fail — 2 vs target 6" — matching what the Journal entry already showed. `ui/shell.js`\'s `performFieldRoll` (\'flat\' branch) only — Starforged/Traveller toasts unchanged, not reported as an issue.',
    'Phase 6 complete — Narrative Trackers: two new campaign-level dials, Resources and Reputation (context.what, alongside threat/mystery — same "GM-set gauge the Co-Pilot reads" pattern, defaulting to a neutral 5/10 midpoint rather than 0 so an old save never suddenly reads as destitute or reviled). New Shift Story actions (Gain/Spend Resources, Raise/Lower Reputation) and two range sliders on the WHAT view. The Co-Pilot now reacts to both: critically low Resources surfaces a scarcity observation/consequence and points at the Trade & Cargo > Cargo Problem oracle table; soured Reputation surfaces as an observation/consequence about closed doors and refused help; abundant Resources or high Reputation open a new opportunity line (a favor, discount, or the room to be generous). This closes out Phase 6 (Campaign Continuity) — Session Recap, Thread lifecycle, and "What did I overlook?" all shipped in prior builds this phase.',
    'Attribute fields (Edge, Combat, Speed, ...) redesigned: the +/- steppers are gone in favor of a directly-editable, numerically-validated input (no min/max clamp — a modifier can go negative or past an old 1-5 scale). Three per-field display formats, editable in Settings\' Bestiary template editor: sign ("+3", Starforged-style, default), inches ("3\"", 5PFH Speed-style), plain ("3"). The field\'s LABEL is now the roll trigger (click "EDGE" to roll); a field with no roll method gets a plain, non-clickable label. Four dice models now available (none/Starforged d6-vs-2d10/5PFH d6-vs-target/new Traveller 2d6-vs-target, domain/dice.js\'s rollTraveller) — room is left to add more (5PFH Planetfall, Stars Without Number) as those systems get authored mechanics. 5PFH\'s Speed field ships as the concrete example: inches-formatted, not rollable.',
    'Phase 6 continued — Thread lifecycle: domain/threads.js threads now carry a 7-state narrative stage (Seeded/Active/Escalating/Dormant/Converging/Resolved/Archived) and a low/normal/high priority, GM-set via dropdowns on the Threads block (WHY question) — never auto-inferred, except that filling a clock still auto-marks it Resolved (unchanged prior behavior). "What did I overlook?" — a new Co-Pilot card (observation-only, never auto-correcting) surfaces threads gone quiet (Dormant, or untouched since creation), excluding ones already Resolved/Archived.',
    'Rules Constitution — requirements/initial design inputs/gameplay-goals.md sharpened "genre-aware, not genre-locked" into a concrete claim: every ruleset is a content provider, not the application. data/rulesConstitution.js records six named systems (Starforged, Traveller, Five Parsecs From Home, Hostile, Stars Without Number, Planetfall) mapped to gameplay areas, plus four responsibilities reserved for Saga Atlas itself (campaign memory, story continuity, rules switching, recommendations) — never delegated to a ruleset. Surfaced read-only in Settings; each provider honestly status-tagged (two of the six have zero authored data yet). Reference for Phase 9\'s future Activity → Rules Lens recommender, not an engine built ahead of its turn — see docs/adr/0002.',
    'Phase 6 (Campaign Continuity) begins — Session Recap ("Previously on...", domain/recap.js): one click in the Journal drawer composes what happened last time, open threads, the current objective, relevant entities, pressure, and a Co-Pilot recommendation from data already kept; "Save as Journal note" files it, excluding prior recaps from its own recap. Pure, read-only, and tested. Remaining Phase 6 items (Narrative Trackers beyond threat/mystery) are still open.',
    'Statblock polish — Bestiary is now explicitly an NPC subtype (like Character): statblock add-choices are scoped by entity type (Character Sheet/Bestiary only for NPCs, Vehicle Stats only for Assets; other entity types get no statblock options). Attribute/stat fields (Edge, Combat, ...) now render as a single signed number with +/- steppers instead of a 1-5 click-to-set meter — matching how Starforged/5PFH sheets actually present a stat; the 1-5 track remains for genuine depleting resources (Health, Hull). The "+ Add a statblock" chip row collapses behind a gear icon to save space once a few groups exist.',
    'Statblock redesign — an entity now holds an ARRAY of statblock groups (entity.statblocks) instead of one: a character can carry both a Starforged and a 5PFH sheet, or an NPC two Bestiary templates, simultaneously — adding one is always additive (a "+ Add" chip row), never a toggle that replaces another\'s data; each group is removable on its own via its own trash icon. Per-field UI simplified to label + value only — the rename input and the ★ (attribute)/Aa (track)/✕ (remove) buttons are gone from the entity view, since a field\'s name/kind is now fixed by its template (Settings owns that); ad-hoc "+ Field"/"+ Track" additions are named via a one-time prompt instead of an inline-editable label.',
    'Phase 5 audit — browser-verified every Phase 5 feature end to end (Playwright against the real bundle). Found and fixed one real bug: the in-app PDF viewer\'s close button was rendered but unclickable — the always-open Documents drawer sat at a higher z-index and physically overlapped it. The viewer now insets its right edge by the current drawer\'s width instead of extending underneath it.',
    'Phase 5 — design review pass against PROGRESS.md USER NOTES: three new drawers — Party (NPC #character roster + party-wide resource trackers), Colony (5PFH Planetfall turn sheet, entity-referencing crew roster, #lifeform encounter filter), Guide (freeform @mention/@[Doc]-linked reference document). Oracle drawer rebuilt as a grouped, collapsible, searchable tree (was a flat un-filterable list — the search box was silently broken). Bestiary statblock templates: per-game-system NPC field manifests (kind, roll method, sort order) editable in Settings, with a per-NPC template selector so a Bestiary can assign the right ruleset per creature; attribute badges now show a signed value ("EDGE +3"). Document Library: multi-file upload, tags + tag-filter + search, rename-the-label (not the file) via an edit button, name-as-link opening an in-app PDF viewer panel (not a new tab) beside the drawer. Entity relationships gained an editable free-text note per link. Fixed: a missing import that threw whenever the Journal rendered an entry with a @[Document] mention; the service worker cache-first strategy that could mask a rebuilt bundle indefinitely (now network-first); a GitHub Pages deploy of this repo having no dist/ bundle at all (added a build+deploy Actions workflow).',
    'Phase 4 — Document Library: assets/docs/ is auto-scanned at build time into a Reference Library (rulebooks/settings PDFs, always current with the folder); the docs drawer also supports real file uploads (stored as data URLs) alongside text notes. Character Sheets: a ruleset-driven statblock kind (Starforged or 5PFH, chosen in Settings > Stat system) builds a full rollable stat/resource-track sheet in one click, switchable between rulesets; an optional Crew Link link-out lives in Settings for full character-building wizards this app does not replicate.',
    'Phase 3D — statblock fields can be numeric tracks: a Crew-Link-style row of click-to-set boxes, with double-click on the value badge to roll (d6 + value vs 2 challenge dice, filed to the Journal). Health/Hull default to tracks; any field converts with the # / Aa toggle; "+ Track" adds a new one.',
    'Phase 3C — NPC/vehicle statblocks, drag-and-drop entity linking + drop-to-mention in Journal and context fields, this Build panel.',
    'Phase 3B — force-directed relationship graph over entity links, click-through to inspector, live edge-tab badges.',
    'Phase 3A — Entity Inspector + @mention auto-linking; WHO/WHERE cards populate from real entities.',
    'New — Threads (progress clocks) with Co-Pilot awareness.',
    'Phase 2 — interactive cockpit: Continue Story, Shift Story reducers, Oracle + Journal drawers, live Co-Pilot, timeline.',
    'Phase 1 — oracle roll engine, scene generation, context model ported as pure, tested modules.',
    'Phase 0 — single versioned campaign document, lossless migration from v0.53, three-tier cockpit shell.',
  ],
};
