// build.js — a tiny zero-dependency bundler.
//
// Why this exists: browsers block ES module `import` over the file:// protocol
// (CORS, origin "null"). To let the app run by simply double-clicking
// index.html, we bundle the module graph into one classic <script>.
//
// Keeps the clean ES-module source as the source of truth; `npm run build`
// regenerates dist/app.bundle.js. No third-party dependencies (Node stdlib only).

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, posix, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { titleFromFilename } from '../src/domain/titleCase.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = 'src/main.js';

// Scan assets/docs/ so the Docs drawer's Reference Library always reflects
// whatever is actually in the folder — drop a PDF in, rebuild, it shows up.
// Generated file, not committed (see .gitignore), same as dist/. Title
// derivation (extension/hyphen stripping + proper-casing any ALL-CAPS
// filename segments — assets/docs/ naming isn't consistent, see
// "HOSTILE SHORTS 001GhostShip" vs. "Hostile marine sheet") is shared with
// the Documents drawer's own file-upload handler, see titleCase.js.
const DOCS_DIR = join(ROOT, 'assets', 'docs');
const docsManifest = existsSync(DOCS_DIR)
  ? readdirSync(DOCS_DIR)
      .filter((name) => statSync(join(DOCS_DIR, name)).isFile())
      .map((name) => ({
        file: `assets/docs/${name}`,
        title: titleFromFilename(name),
        ext: extname(name).slice(1).toLowerCase(),
        sizeBytes: statSync(join(DOCS_DIR, name)).size,
      }))
      .sort((a, b) => a.title.localeCompare(b.title))
  : [];
mkdirSync(join(ROOT, 'src', 'data'), { recursive: true });
writeFileSync(
  join(ROOT, 'src', 'data', 'docsManifest.js'),
  `// AUTO-GENERATED by scripts/build.js from assets/docs/ — do not edit.\nexport const DOCS_MANIFEST = ${JSON.stringify(docsManifest, null, 2)};\n`
);

function normalizeKey(importerKey, spec) {
  const dir = posix.dirname(importerKey);
  return posix.normalize(posix.join(dir, spec));
}

const modules = new Map(); // key -> transformed body
const queue = [ENTRY];

// If a developer has placed an imported campaign in data/imported-campaign.json
// include it in the bundle as a global `window.__importedCampaign` so the
// app can synchronously load it at startup (useful for persisting imports
// across rebuilds without requiring a server).
const IMPORTED_PATH = 'data/imported-campaign.json';
let importedCampaignJson = null;
if (existsSync(join(ROOT, IMPORTED_PATH))) {
  try { importedCampaignJson = readFileSync(join(ROOT, IMPORTED_PATH), 'utf8'); } catch (e) { importedCampaignJson = null; }
}

while (queue.length) {
  const key = queue.shift();
  if (modules.has(key)) continue;
  let src = readFileSync(join(ROOT, key), 'utf8');

  // Rewrite imports (single- and multi-line) to require() with normalized keys.
  src = src.replace(
    /import\s*\{([\s\S]*?)\}\s*from\s*['"]([^'"]+)['"];?/g,
    (_m, names, spec) => {
      const depKey = normalizeKey(key, spec);
      if (!modules.has(depKey) && !queue.includes(depKey)) queue.push(depKey);
      const clean = names.replace(/\s+/g, ' ').trim();
      return `const {${clean}} = require(${JSON.stringify(depKey)});`;
    }
  );

  // Rewrite exports: `export function foo` / `export async function foo` /
  // `export const BAR` → strip keyword, then re-export by name at the end
  // of the module. (`async function` added 2026-07-06 — ui/mechanicsScan.js
  // was the first module needing an exported async function; before this,
  // every async export used the `export { name }` aggregate form below.)
  const exported = [];
  src = src.replace(/^export\s+(async function|function|const)\s+([A-Za-z0-9_$]+)/gm, (_m, kind, name) => {
    exported.push(name);
    return `${kind} ${name}`;
  });
  // Rewrite aggregate re-exports: `export { A, B };` → record names, drop line.
  src = src.replace(/^export\s*\{([^}]*)\}\s*;?/gm, (_m, names) => {
    names.split(',').map((n) => n.trim().split(/\s+as\s+/).pop().trim()).filter(Boolean).forEach((n) => exported.push(n));
    return '';
  });
  if (exported.length) {
    src += `\n${exported.map(n => `exports.${n} = ${n};`).join('\n')}\n`;
  }

  modules.set(key, src);
}

const registrations = [...modules.entries()]
  .map(([key, body]) => `register(${JSON.stringify(key)}, function(exports, require){\n${body}\n});`)
  .join('\n\n');

  // Build-time embedding: serialize the imported campaign into a small JS
  // snippet so it can be synchronously available to the app at runtime.
  let __embeddedImportedCampaign = '';
  if (importedCampaignJson) {
    __embeddedImportedCampaign = `;(function(){ try{ const data = ${importedCampaignJson}; if (typeof window !== 'undefined') window.__importedCampaign = data; }catch(e){} })();\n`;
  }

const bundle = `/* AUTO-GENERATED by scripts/build.js — do not edit. Run \`npm run build\`. */
${__embeddedImportedCampaign}
(function(){
  "use strict";
  var __cache = {}, __mods = {};
  function register(id, fn){ __mods[id] = fn; }
  function require(id){
    if (__cache[id]) return __cache[id].exports;
    var m = __cache[id] = { exports: {} };
    if (!__mods[id]) throw new Error("module not found: " + id);
    __mods[id](m.exports, require);
    return m.exports;
  }

${registrations}

  require(${JSON.stringify(ENTRY)});
})();
`;

mkdirSync(join(ROOT, 'dist'), { recursive: true });
writeFileSync(join(ROOT, 'dist', 'app.bundle.js'), bundle);
console.log(`bundled ${modules.size} modules -> dist/app.bundle.js (${bundle.length} bytes)`);
