// build.js — a tiny zero-dependency bundler.
//
// Why this exists: browsers block ES module `import` over the file:// protocol
// (CORS, origin "null"). To let the app run by simply double-clicking
// index.html, we bundle the module graph into one classic <script>.
//
// Keeps the clean ES-module source as the source of truth; `npm run build`
// regenerates dist/app.bundle.js. No third-party dependencies (Node stdlib only).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = 'src/main.js';

function normalizeKey(importerKey, spec) {
  const dir = posix.dirname(importerKey);
  return posix.normalize(posix.join(dir, spec));
}

const modules = new Map(); // key -> transformed body
const queue = [ENTRY];

while (queue.length) {
  const key = queue.shift();
  if (modules.has(key)) continue;
  let src = readFileSync(join(ROOT, key), 'utf8');

  // Rewrite imports (single- and multi-line) to require() with normalized keys.
  src = src.replace(
    /import\s*\{([\s\S]*?)\}\s*from\s*['"]([^'"]+)['"];?/g,
    (_m, names, spec) => {
      const depKey = normalizeKey(key, spec);
      if (!modules.has(depKey) && !queue.includes(depKey)) queue.push(depKey);
      const clean = names.replace(/\s+/g, ' ').trim();
      return `const {${clean}} = require(${JSON.stringify(depKey)});`;
    }
  );

  // Rewrite exports: `export function foo` / `export const BAR` → strip keyword,
  // then re-export by name at the end of the module.
  const exported = [];
  src = src.replace(/^export\s+(function|const)\s+([A-Za-z0-9_$]+)/gm, (_m, kind, name) => {
    exported.push(name);
    return `${kind} ${name}`;
  });
  // Rewrite aggregate re-exports: `export { A, B };` → record names, drop line.
  src = src.replace(/^export\s*\{([^}]*)\}\s*;?/gm, (_m, names) => {
    names.split(',').map((n) => n.trim().split(/\s+as\s+/).pop().trim()).filter(Boolean).forEach((n) => exported.push(n));
    return '';
  });
  if (exported.length) {
    src += `\n${exported.map(n => `exports.${n} = ${n};`).join('\n')}\n`;
  }

  modules.set(key, src);
}

const registrations = [...modules.entries()]
  .map(([key, body]) => `register(${JSON.stringify(key)}, function(exports, require){\n${body}\n});`)
  .join('\n\n');

const bundle = `/* AUTO-GENERATED by scripts/build.js — do not edit. Run \`npm run build\`. */
(function(){
  "use strict";
  var __cache = {}, __mods = {};
  function register(id, fn){ __mods[id] = fn; }
  function require(id){
    if (__cache[id]) return __cache[id].exports;
    var m = __cache[id] = { exports: {} };
    if (!__mods[id]) throw new Error("module not found: " + id);
    __mods[id](m.exports, require);
    return m.exports;
  }

${registrations}

  require(${JSON.stringify(ENTRY)});
})();
`;

mkdirSync(join(ROOT, 'dist'), { recursive: true });
writeFileSync(join(ROOT, 'dist', 'app.bundle.js'), bundle);
console.log(`bundled ${modules.size} modules -> dist/app.bundle.js (${bundle.length} bytes)`);
